# Generated by Django 4.2.4 on 2023-08-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('cpassword', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('gender', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
    ]
