# Generated by Django 4.2.4 on 2023-09-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('messages', models.CharField(max_length=400)),
            ],
        ),
    ]
