# Generated by Django 4.2.4 on 2023-09-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='c_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=40)),
                ('l_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('zip_p', models.BigIntegerField()),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('gst_no', models.CharField(max_length=40)),
                ('cln', models.BigIntegerField()),
                ('job', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=40)),
                ('salary', models.IntegerField()),
                ('subject', models.CharField(max_length=90)),
                ('iso_c', models.BinaryField()),
                ('gmp_c', models.BinaryField()),
                ('logo', models.BinaryField()),
            ],
        ),
    ]
