# Generated by Django 4.2.4 on 2023-09-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0005_c_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='sp_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('pass1', models.CharField(max_length=40)),
                ('pass2', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('gender', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
            ],
        ),
    ]
