# Generated by Django 4.2.4 on 2023-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0006_sp_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='sp_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField()),
                ('title', models.CharField(max_length=40)),
                ('sp_new', models.CharField(max_length=500)),
            ],
        ),
    ]
