# Generated by Django 4.2.4 on 2023-09-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0007_sp_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp_news',
            name='sp_new',
            field=models.CharField(max_length=5000),
        ),
    ]
