# Generated by Django 4.2.4 on 2023-10-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0008_alter_sp_news_sp_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=60)),
                ('opt1', models.CharField(max_length=40)),
                ('opt2', models.CharField(max_length=40)),
                ('opt3', models.CharField(max_length=40)),
                ('opt4', models.CharField(max_length=40)),
                ('answer', models.CharField(max_length=40)),
            ],
        ),
    ]
