# Generated by Django 4.2.6 on 2023-10-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0012_s_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s_payment',
            name='phone',
        ),
        migrations.AddField(
            model_name='s_payment',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
