# Generated by Django 4.2.6 on 2023-10-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0013_remove_s_payment_phone_s_payment_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_payment',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
